[versions]
#jetbrains
eventbusVersion = "3.3.1"
expressAudioVersion = "3.15.0"
kotlin = "1.9.0"
kotlinxSerializationJson = "1.5.1"
#Simple tools
simple-commons = "eceb48949e"
#Gradle
gradlePlugins-agp = "8.5.0"
#Other
indicatorFastScroll = "4524cd0b61"
autofitTextView = "0.2.1"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "com.simplemobiletools.dialer"
app-version-versionCode = "1"
app-version-versionName = "1.0.0"
[libraries]
#Simple Mobile Tools
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbusVersion" }
express-audio = { module = "im.zego:express-audio", version.ref = "expressAudioVersion" }
simple-tools-commons = { module = "com.github.SimpleMobileTools:Simple-Commons", version.ref = "simple-commons" }
#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#Other
indicator-fast-scroll = { module = "com.github.tibbi:IndicatorFastScroll", version.ref = "indicatorFastScroll" }
autofit-text-view = { module = "me.grantland:autofittextview", version.ref = "autofitTextView" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
